Database:
  Class: SQLiteDB
  db_path: ./data/database.db

Components:
  Mail:
    Class: QQMail
    enable: ture
    args:
      sender_mail: XXXX@XXX.com
      sender_name: XXXX
      password: XXXXXXXXXX

  WebMessenger:
    Class: WebMessengerTCP
    args:
      server_port: 9999