Database:
  Class: SQLiteDB
  db_path: ./data/database.db

Docker:
  repository: 'abc.com/repository'

Components:
  Mail:
    Class: QQMail
    enable: ture
    args:
      sender_mail: XXXX@XXX.com
      sender_name: XXXX
      password: XXXXXXXXXX

  WebMessenger:
    Class: WebMessengerTCP
    args:
      port: 9999

Dispatch:
  Class: FCFS
  args: {}

