MachineID: m0
# 应保证每台部署的机器都重新生成应该uuid, 如shell 命令 uuidgen
URL: '192.168.120.128'
# 用于访问机器的url,可以是网址或ip

Components:
  WebMessenger: 
    Class: GPUMessengerWS
    args:
      host: 127.0.0.1
      port: 10000
      path: "ws/server"
