Database:
  Class: SQLiteDB
  db_path: ./data/database.db

Docker:
  repository: 'abc.com/repository'
  rmimageafterbuild: false

Components:
  Mail:
    Class: QQMail
    enable: ture
    args:
      sender_mail: XXXX@XXX.com
      sender_name: XXXX
      password: XXXXXXXXXX

  WebMessenger:
    Class: WebMessengerTCP
    args:
      port: 10001
  
  Logger:
    enable: ture
    args:
      filename: ./data/log.txt

  ErrorLogger:
    enable: ture
    args:
      filename: ./data/error.txt

Dispatch:
  Class: FCFS
  args: {}

